### PR TITLE
fix(parseArgs): Avoid template constraint to provide a better error m…

### PR DESCRIPTION
**Pull request by Geod24**
…essage

Currently, when a user's main does not compile, they get a barely readable error message, which looks like:
```
argparse/source/argparse/api/cli.d(196,65): Error: none of the overloads of `parseArgs` are callable using argument types `(string[])`
argparse/1.4.1/argparse/source/argparse/api/cli.d(93,19):        Candidates are: `argparse.api.cli.CLI!(Config('=', '\xff', '-', "--", true, false, true, StylingMode.autodetect, null, Style(TextStyle([cast(ubyte)1u]), TextStyle([cast(ubyte)1u]), TextStyle([cast(ubyte)1u, cast(ubyte)4u]), TextStyle([cast(ubyte)93u]), TextStyle([cast(ubyte)3u]), TextStyle([cast(ubyte)93u])), null), Arguments).parseArgs(ref Arguments receiver, string[] args)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(105,16):                        `parseArgs(alias newMain)(string[] args, auto ref COMMAND initialValue = COMMAND.init)`
  with `newMain = __lambda_L92_C27(__T1)(args)`
  must satisfy the following constraint:
`       __traits(compiles, ()
{
newMain(initialValue);
}
)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(123,16):                        `parseArgs(alias newMain)(string[] args, auto ref COMMAND initialValue = COMMAND.init)`
  with `newMain = __lambda_L92_C27(__T1)(args)`
  must satisfy the following constraint:
`       __traits(compiles, ()
{
newMain(initialValue, string[].init);
}
)`
source/main.d(92,1):        parent scope from here: `mixin main!((args)
{
return args.cmd.match!((CSACommand cmd)
{
return createServiceAccount(cmd);
}
, (SyncIDCommand cmd)
{
return synchronizeIdentities(cmd);
}
, (SyncHierarchyCommand cmd)
{
return 0;
}
, (DefaultCmd cmd)
{
Arguments dummy;
CLI!Arguments.parseArgs(dummy, ["-h"]);
return 1;
}
);
}
)`
```
This is because none of the `__traits(compiles)` on the template constraints matches. By not using those constraints, and having a fallback to a simple call, we instead get the following error message:
```
std/sumtype.d(1983,13): Error: static assert:  "`handlers[2]` of type `int function(SyncHierarchyCommand cmd) pure nothrow @nogc @safe` never matches. Perhaps the handler failed to compile"
std/sumtype.d(1647,52):        instantiated from here: `matchImpl!(SumType!(CSACommand, SyncIDCommand, Default!(DefaultCmd)))`
source/main.d(94,20):        instantiated from here: `match!(SumType!(CSACommand, SyncIDCommand, Default!(DefaultCmd)))`
argparse/1.4.1/argparse/source/argparse/api/cli.d(122,20):        instantiated from here: `__lambda_L92_C27!(Arguments)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(182,65):        instantiated from here: `parseArgs!(__lambda_L92_C27)`
```

In this instance, the error becomes much easier to spot (said user added a subcommand, but forgot to add it to the sumtype).

### CODE REVIEW

**Comment by andrey-zherikov** [comment]
This is definitely in my todo list. Thank you for fixing it.

Although I don't have objections to your solution, just wondering, from user's POV how bad would it be if `newMain` parameter is moved from template to runtime args? Something like
```d
int parseArgs(RETURN)(string[] args, RETURN function(COMMAND) newMain)
int parseArgs(RETURN)(string[] args, RETURN function(COMMAND, string[]) newMain)
```
So if `newMain` doesn't match either of them then compiler will clearly error out.

**Comment by Geod24** [comment]
It would definitely improve the situation! I think Phobos' approach of having lambda passed as template argument is very prone to bloat, and passing them as runtime parameter is in my experience more user-friendly. However I would consider templating the whole function type to support delegates. This is however a breaking change but IIUC you're currently preparing for v2 ?

**Comment by andrey-zherikov** [comment]
Yes, I'm working on v2.0 and we can still put breaking changes. I'd suggest to deprecate existing API and add new with runtime parameters.

**Comment by andrey-zherikov** [comment]
@Geod24 Will you be able to add new version of CLI API (that take function as runtime parameter)?

**Comment by Geod24** [comment]
@andrey-zherikov : Do you want to keep support for non-copyable struct ? Because that adds extra `ref` overloads.

**Comment by SirNickolas** [comment]
> However I would consider templating the whole function type to support delegates.

Ref/non-ref callables don’t pose a problem if you templatize over the whole function type, do they? Could you explain what those extra overloads are?

**Comment by andrey-zherikov** [comment]
> @andrey-zherikov : Do you want to keep support for non-copyable struct ? Because that adds extra `ref` overloads.

Not sure what extra overloads you need. I thought it would look like this:
```d
int parseArgs(NEWMAIN)(string[] args, NEWMAIN newMain)
{
return parseArgs(args, COMMAND.init, newMain);
}
int parseArgs(NEWMAIN)(string[] args, auto ref COMMAND initialValue, NEWMAIN newMain)
{
...
}
```

**Comment by Geod24** [comment]
Templating the function type "naively" would run into the same problem:

```d
void parseArgs (FUNCT) (string[] args, scope FUNCT dg) {
 	dg(args);   
}

void main () {
 	parseArgs(null, (args) => args + 1);   
}
```

```
onlineapp.d(6): Error: template `parseArgs` is not callable using argument types `!()(typeof(null), void)`
onlineapp.d(1):        Candidate is: `parseArgs(FUNCT)(string[] args, scope FUNCT dg)`
```

I'll try a few options.

**Comment by Geod24** [comment]
Compare that to:
```d
void parseArgs (string[] args, scope void function(string[]) dg) {
 	dg(args);   
}

void main () {
 	parseArgs(null, (args) => args + 1);   
}
```

```
onlineapp.d(6): Error: incompatible types for `(args) + (1)`: `string[]` and `int`
onlineapp.d(6): Error: function `parseArgs` is not callable using argument types `(typeof(null), void)`
onlineapp.d(6):        cannot pass argument `__lambda1` of type `void` to parameter `scope void function(string[]) dg`
onlineapp.d(1):        `onlineapp.parseArgs(string[] args, scope void function(string[]) dg)` declared here
```

Problem is, we have the following dimensions:
- `int` vs `void` return type;
- `function` vs `delegate`;
- `ref` vs non-`ref` command;
- Single vs double arguments;

Which means we end up with 16 overloads if we do not template.

**Comment by SirNickolas** [comment]
Oh, right. If we templatize the whole type of `newMain`, we lose the ability to infer its parameter types when `newMain` is a lambda.

> `int` vs `void` return type;

Well, this can be dealt with via a template, as shown in the [first comment]. So there are 8 overloads left.

> `ref` vs non-`ref` command;

By the way, dropping support for `newMain` taking `ref COMMAND` does not require dropping support for non-copyable structs. We just need to [move] the struct into `newMain`. That’s still a breaking change, but the fix at user’s side is trivial (just remove `ref`).

And that leaves us with 4 overloads: `function`/`delegate` × 1-/2-parameter. More or less manageable, isn’t it?

[first comment]: https://github.com/andrey-zherikov/argparse/pull/212#issuecomment-2843229378
[move]: https://dlang.org/phobos/core_lifetime.html#.move

File: source/argparse/api/cli.d [hunk 1]
```diff
@@ -122,38 +122,32 @@ template CLI(Config config, COMMAND)
...
+        static if(__traits(compiles, { newMain(initialValue, string[].init); })) {
+            auto res = parseKnownArgs(value, args);
+            if(!res)
+                return res.exitCode;
+            static if(__traits(compiles, { int a = cast(int) newMain(value, args); }))
+                return cast(int) newMain(value, args);
+            else {
+                newMain(value, args);
+                return 0;
+            }
```
Comment (SirNickolas) [inline source/argparse/api/cli.d:140]: I think this condition should be flipped: if `newMain` returns something not convertible to `int`, we should not silently discard it.

```d
static if(is(typeof(newMain(value, args)) == void))
{
    newMain(value, args);
    return 0;
}
else
    return cast(int) newMain(value, args);
```

Probably add `|| !__traits(compiles, newMain(value, args))` if it improves error messages.

Same for 1-parameter variant of `newMain`.

**Comment by Geod24** [comment]
Sorry for the delay on this. Haven't had time to dedicate to argparse yet, but I would indeed like to take a look at various aspect (including this PR) this week hopefully.

**Comment by Geod24** [comment]
> Well, this can be dealt with via a template, as shown in the https://github.com/andrey-zherikov/argparse/pull/212#issuecomment-2843229378. So there are 8 overloads left.

No, anything that moves it to a template will result in bad error message. It is really a limitation of D here, and you can see this kind of issues with `std.algorithm` quite easily.

> By the way, dropping support for newMain taking ref COMMAND does not require dropping support for non-copyable structs. We just need to [move](https://dlang.org/phobos/core_lifetime.html#.move) the struct into newMain. That’s still a breaking change, but the fix at user’s side is trivial (just remove ref).

@andrey-zherikov : Is that something you'd like ? If we are to think past the current MR, my recommendation would be:
1) Don't take the command as an argument - let `argparse` construct it, this way you can support `const` or `immutable` members, and assume the user have populated them via the constructor;
2) Change `argparse` to assume that when `COMMAND.init.myField != typeof(COMMAND.field).init`, the value is optional;

This in my experience has been great defaults to have in Configy. I'd recommend to use something like [this](https://github.com/dlang-community/configy/blob/699128f63ed72b3654380f85a88fd58509114693/source/configy/fieldref.d) though.

**Comment by andrey-zherikov** [comment]
> @andrey-zherikov : Is that something you'd like ?

If it makes users happier - I'm fine.

> 1. Don't take the command as an argument - let `argparse` construct it, this way you can support `const` or `immutable` members, and assume the user have populated them via the constructor;

The only constructor that `argparse` will be able to call is default one and it's not allowed to be user-defined

> 2\. Change `argparse` to assume that when `COMMAND.init.myField != typeof(COMMAND.field).init`, the value is optional;

I thought about this some time ago and it wasn't clear what benefits it would provide over the current design. Could you provide an example where we can see this benefit?

**Comment by andrey-zherikov** [comment]
> * `function` vs `delegate`;

Are we sure we need `function`? Won't `delegate` be enough?

**Comment by Geod24** [comment]
> Are we sure we need `function`? Won't `delegate` be enough?

Unfortunately not (IMO). Especially for `main`, it is *less* likely to have a context pointer than to have one in my (limited) experience.

> The only constructor that argparse will be able to call is default one and it's not allowed to be user-defined

True, but users can set default values to field if those values are CTFE-able. I fail to see a case where I would want to set a non-CTFEable value *before* argument parsing. I can think of a few cases where I would want one *after* argument parsing though.

> I thought about this some time ago and it wasn't clear what benefits it would provide over the current design. Could you provide an example where we can see this benefit?

On taking a second look, only positional arguments are mandatory by default, right ? Which makes the most sense.

Note that I have hit a dead end with the current PR. Because we have the following:
```D
    template main(alias newMain)
    {
        version(argparse_completion)
        {
            mixin CLI!(config, COMMAND).mainComplete;
        }
        else
        {
            int main(string[] argv)
            {
                return CLI!(config, COMMAND).parseArgs(argv[1..$], newMain);
            }
        }
    }
```

Now `newMain` is essentially a template. E.g. there's the following unittest:
```D
    // Ensure that CLI.main is compilable
    { mixin CLI!(cfg, Args).main!((_                  ){}); }
    { mixin CLI!(cfg, Args).main!((_, string[] unknown){}); }
    { mixin CLI!(cfg, Args).main!((_                  ){ return 123; }); }
    { mixin CLI!(cfg, Args).main!((_, string[] unknown){ return 123; }); }
```

All of those pass templates to `main` which you can't *sanely* turn into a delegate. Will try another approach.

**Comment by Geod24** [comment]
> Completion part of API can follow parsing API. I don't see a problem here

No the problem was from `alias` template parameter to `delegate` / `function`, not the completion API. But I think I found a solution.

**Comment by Geod24** [comment]
Uploaded a runtime-only option. Not very happy with it, and had to drop support for non-copyable structs because of what is likely a frontend bug, but leaving it out for comment.

File: source/argparse/api/cli.d [hunk 2]
```diff
@@ -121,42 +121,148 @@ template CLI(Config config, COMMAND)
...
+     *   args = The CLI arguments as provided to `main`
+     *   newMain = The main function to call if argument parsing is successful
+     *   initialValue = An optional initial state for the `COMMAND` struct
+     *
+     * Returns:
+     *   The return value of `newMain`, or `0` if `newMain` returns `void`.
+     *   If any unrecognized argument is provided, returns a non-zero value.
+     */
+    static int parseArgs(string[] args, scope int delegate(ref COMMAND) newMain,
+            auto ref COMMAND initialValue = COMMAND.init) {
```
Comment (andrey-zherikov) [inline source/argparse/api/cli.d:140]: I think having `initialValue` as last argument makes it unclear when used. Imagine this code:
```d
parseArgs(args, (args)
  {
  ...
  ...
  ...
  many many lines
  ...
  ...
  ...
  }, myInitialValue);
```

I think it will be better to have two functions:
```d
parseArgs(string[] args, COMMAND initValue, ... newMain) {...}
parseArgs(string[] args, ... newMain) => parseArgs(args, COMMAND.init, newMain);

```

**Review by andrey-zherikov — COMMENTED** [review]
While I was looking at code changes, I got two ideas that (I think) worths some discussion:
1. Maybe get rid of `CLI(Config, COMMAND)` and replace with top-level functions like
  ```d
  Result parseArgs(Config config, COMMAND)(ref COMMAND receiver, string[] args) {...}
  ```
  ?

2. Support custom processing of errors, something like this:
  ```d
  parseArgs(args)  // parses CLI and returns `Result` object
    .onError(_ => stderr.writeln(_))  // call custom function in case of parsing error
    .onSuccess(_ => _.writeln);  // call "newMain" in case of successful parsing
  ```
  This maybe too much and below is good enough:
  ```d
  auto res = parseArgs(args)  // parses CLI and returns `Result` object
  if(!res)
    stderr.writeln(res.errors))  // note: there is no "errors" available atm

  // new main goes here
  ```

**Comment by andrey-zherikov** [comment]
Is a variant of `parseArgs` with `newMain` actually useful? More I'm thinking about it - more I'm coming to conclusion that if user wants to provide newMain then the "main" mixin should be actually used.

**Comment by andrey-zherikov** [comment]
> your suggestion is to simply remove those two functions ?

Yes

**Comment by andrey-zherikov** [comment]
I tried to add overrides for `main` template but parameter overriding doesn't work the way I'd expect. Posted this [on forum](https://forum.dlang.org/thread/edmdjgtjrejqxyekwndn@forum.dlang.org)

**Comment by andrey-zherikov** [comment]
I think I came up with (I hope) good solution. I added `main1` template to show what I mean. In addition to that, I think to remove `parseArgs` functions that accept `newMain` as I mentioned above.

File: source/argparse/api/cli.d [hunk 3]
```diff
@@ -193,7 +299,52 @@ template CLI(Config config, COMMAND)
...
+            static if (is(typeof(newMain(value))))
+            {
+                // newMain has one parameter so strictly parse command line
+                auto res = CLI!(config, COMMAND).parseArgs(value, argv);
+            }
+            else
+            {
+                // newMain has two parameters so parse only known arguments
+                auto res = CLI!(config, COMMAND).parseKnownArgs(value, argv);
+            }
```
[the remark this answers is not in the document]
Comment (andrey-zherikov) [reply source/argparse/api/cli.d:325]: I have no objections
